# Generated by Django 5.1 on 2024-09-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(default='events.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NonSuperUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='events.jpg', upload_to='')),
                ('owner_commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.event')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='secretary', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('contact_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=255)),
                ('name_of_emergency_contact', models.CharField(max_length=255)),
                ('relationship_to_secretary', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('son', 'Son'), ('daugter', 'Daughter'), ('others', 'Others')], max_length=255)),
                ('emergency_contact_number', models.IntegerField()),
                ('highest_educational_attainment', models.CharField(choices=[('elementary', 'Elementary'), ('highschool', 'Highschool'), ('college', 'College')], max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(default='secretary.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Secretaries',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(default='house name', max_length=255)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(default='pope-francis-village.png', upload_to='')),
                ('property_block_no', models.IntegerField()),
                ('property_house_no', models.IntegerField(unique=True)),
                ('property_description', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('family', 'Family')], max_length=255)),
                ('bathroom', models.IntegerField(default=0)),
                ('bedroom', models.IntegerField(default=0)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under maintenance')], default='available', max_length=255)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('household_head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_head', to='ADMIN.nonsuperuser')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
